use_frameworks!


target 'HeyLogKit_Example' do
  platform :ios, '13.0'
  pod 'HeyLogKit/iOS', :path => '../'
end


target 'HeyLogKit_MacDemo' do
  platform :macos, '10.13'
  pod 'HeyLogKit/OSX', :path => '../'
end


#target 'HeyLogKit_Tests' do
#  inherit! :search_paths
#end

