use_frameworks!

platform :ios, '10.0'

target 'HeyLogKit_Example' do
  pod 'HeyLogKit', :path => '../'
  
  target 'HeyLogKit_MacDemo' do
    pod 'HeyLogKit', :path => '../'
  end

  target 'HeyLogKit_Tests' do
    inherit! :search_paths

    
  end
end
